# yaml-language-server: $schema=https://json.schemastore.org/drone.json
name: deploy
kind: pipeline
type: docker
node:
  instance: system
trigger:
  event:
    - push
  branch:
    - main
steps:
  - name: deploy
    image: docker:23.0.1-cli-alpine3.17@sha256:379551355fe864c1af00ef1cb80198e47b413c3dbc6787b4719529a71194d86d
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - echo -n "$${ENV}" > .env
      - docker compose --project-name=gammafogtypecom up --detach
      - docker image prune --all --filter=until=24h --force
    environment:
      ENV:
        from_secret: ENV
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
---
name: renovate
kind: pipeline
type: docker
clone:
  disable: true
trigger:
  event:
    - cron
  cron:
    - renovate
steps:
  - name: renovate
    image: renovate/renovate:35.2.3@sha256:b2450d1eb9bc85892c678a6ed3eaf42adbdc0337feed17508b373230881c4515
    commands:
      - renovate
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://git.fogtype.com/api/v1/
      RENOVATE_AUTODISCOVER: "true"
      RENOVATE_AUTODISCOVER_FILTER: "nebel/!(archive.fogtype.com)"
      RENOVATE_TOKEN:
        from_secret: RENOVATE_TOKEN
