# yaml-language-server: $schema=https://json.schemastore.org/drone.json
name: default
kind: pipeline
type: docker
trigger:
  event:
    - push
  branch:
    - main
steps:
  - name: deploy
    image: docker
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - echo -n "$${ENV}" > .env
      - docker compose --project-name=gammafogtypecom up --detach
    environment:
      ENV:
        from_secret: ENV
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
