# yaml-language-server: $schema=https://json.schemastore.org/drone.json
name: deploy
kind: pipeline
type: docker
node:
  instance: system
trigger:
  event:
    - push
  branch:
    - main
steps:
  - name: deploy
    image: docker:23.0.1-cli-alpine3.17@sha256:86c5fc7fcb79efe22a12c4b4329f66f37d2827699a90684c08ba72ef18c881bb
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - echo -n "$${ENV}" > .env
      - docker compose --project-name=gammafogtypecom up --detach
      - docker image prune --all --filter=until=24h --force
    environment:
      ENV:
        from_secret: ENV
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
---
name: renovate
kind: pipeline
type: docker
clone:
  disable: true
trigger:
  event:
    - cron
  cron:
    - renovate
steps:
  - name: renovate
    image: renovate/renovate:34.154.2@sha256:8fbdf847976749c105283d9852276ed0f91100c7a93fd89e096e6b5db5be0eae
    commands:
      - renovate
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://git.fogtype.com/api/v1/
      RENOVATE_AUTODISCOVER: "true"
      RENOVATE_AUTODISCOVER_FILTER: "nebel/!(archive.fogtype.com)"
      RENOVATE_TOKEN:
        from_secret: RENOVATE_TOKEN
