# yaml-language-server: $schema=https://json.schemastore.org/drone.json
name: deploy
kind: pipeline
type: docker
node:
  instance: system
trigger:
  event:
    - push
  branch:
    - main
steps:
  - name: deploy
    image: docker:20.10.22-cli-alpine3.17@sha256:75026b00c823579421c1850c00def301a6126b3f3f684594e51114c997f76467
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - echo -n "$${ENV}" > .env
      - docker compose --project-name=gammafogtypecom up --detach
      - docker image prune --all --filter=until=24h --force
    environment:
      ENV:
        from_secret: ENV
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
---
name: renovate
kind: pipeline
type: docker
clone:
  disable: true
trigger:
  event:
    - cron
  cron:
    - renovate
steps:
  - name: renovate
    image: renovate/renovate:34.101.0@sha256:5c83592149a933aad385c1a068945d51491d64a052f5299ecb5e9c7d46d9c174
    commands:
      - renovate
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://git.fogtype.com/api/v1/
      RENOVATE_AUTODISCOVER: "true"
      RENOVATE_AUTODISCOVER_FILTER: nebel/*
      RENOVATE_TOKEN:
        from_secret: RENOVATE_TOKEN
