# yaml-language-server: $schema=https://json.schemastore.org/drone.json
name: deploy
kind: pipeline
type: docker
node:
  instance: system
trigger:
  event:
    - push
  branch:
    - main
steps:
  - name: deploy
    image: docker:20.10.22-cli-alpine3.17@sha256:fde7a4a9b1ca994f7c5bfd62fb32c70fddbbfea43a1ea74b029d7a88c6f0e243
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - echo -n "$${ENV}" > .env
      - docker compose --project-name=gammafogtypecom up --detach
    environment:
      ENV:
        from_secret: ENV
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
---
name: renovate
kind: pipeline
type: docker
clone:
  disable: true
trigger:
  event:
    - cron
  cron:
    - renovate
steps:
  - name: renovate
    image: renovate/renovate:34.84.2@sha256:1a1f1946218eda836c6ba15cae19e94be03122026e270429b618313591a983f5
    commands:
      - renovate
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://git.fogtype.com/api/v1/
      RENOVATE_AUTODISCOVER: "true"
      RENOVATE_AUTODISCOVER_FILTER: nebel/*
      RENOVATE_TOKEN:
        from_secret: RENOVATE_TOKEN
