# yaml-language-server: $schema=https://json.schemastore.org/drone.json
name: deploy
kind: pipeline
type: docker
trigger:
  event:
    - push
  branch:
    - main
steps:
  - name: deploy
    image: docker
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - echo -n "$${ENV}" > .env
      - docker compose --project-name=gammafogtypecom up --detach
    environment:
      ENV:
        from_secret: ENV
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
---
name: renovate
kind: pipeline
type: docker
clone:
  disable: true
trigger:
  event:
    - cron
    - custom
  cron:
    - renovate
steps:
  - name: deploy
    image: renovate/renovate
    commands:
      - renovate
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://git.fogtype.com/api/v1/
      RENOVATE_AUTODISCOVER: "true"
      RENOVATE_AUTODISCOVER_FILTER: nebel/*
      RENOVATE_TOKEN:
        from_secret: RENOVATE_TOKEN
