# yaml-language-server: $schema=https://json.schemastore.org/drone.json
name: deploy
kind: pipeline
type: docker
node:
  instance: system
trigger:
  event:
    - push
  branch:
    - main
steps:
  - name: deploy
    image: docker:20.10.23-cli-alpine3.17@sha256:2655039c6abfc8a1d75978c5258fccd5c5cedf880b6cfc72077f076d0672c70a
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - echo -n "$${ENV}" > .env
      - docker compose --project-name=gammafogtypecom up --detach
      - docker image prune --all --filter=until=24h --force
    environment:
      ENV:
        from_secret: ENV
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
---
name: renovate
kind: pipeline
type: docker
clone:
  disable: true
trigger:
  event:
    - cron
  cron:
    - renovate
steps:
  - name: renovate
    image: renovate/renovate:34.113.0@sha256:9157c23b1032d9fc24a769ac001da73b9a7d9f932022eab8f31bc778ff181945
    commands:
      - renovate
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://git.fogtype.com/api/v1/
      RENOVATE_AUTODISCOVER: "true"
      RENOVATE_AUTODISCOVER_FILTER: "nebel/!(archive.fogtype.com)"
      RENOVATE_TOKEN:
        from_secret: RENOVATE_TOKEN
